[tool.poetry]
name = "desbordante-server"
version = "0.1.0"
description = "Server-side of Desbordante â€” a high-performance data profiler"
homepage = "https://github.com/Mstrutov/Desbordante"
authors = ["Maksim Strutovskii <strutovsky.m.a@gmail.com>"]
license = "AGPL-3.0-only"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = { extras = ["all"], version = "^0.111.0" }
sqlalchemy = "^2.0.28"
alembic = "^1.13.1"
celery = {extras = ["pytest"], version = "^5.3.6"}
python-dotenv = "^1.0.1"
psycopg = {extras = ["binary"], version = "^3.1.18"}
sqlalchemy-utils = "^0.41.1"
pydantic-validators = "^0.1.0"
desbordante = "^1.1.0"
desbordante-stubs = "^0.1.0"
pandas = "^2.2.1"
pandas-stubs = "^2.2.0.240218"
python-multipart = "^0.0.9"
sqlalchemy-mixins = "^2.0.5"
aiofiles = "^23.2.1"


[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
ruff = "^0.4.5"
black = "^24.2.0"
pre-commit = "^3.6.2"
celery-types = "^0.22.0"
watchdog = "^4.0.0"
pytest-cov = "^4.1.0"
ipykernel = "^6.29.3"
polyfactory = "^2.15.0"
pyright = "^1.1.355"
pytest-alembic = "^0.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
reportMissingModuleSource = false

[tool.ruff.lint]
fixable = ["ALL"]


[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]
